language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache/
    - vendor/

services:
  - mysql

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
  allow_failures:
    - php: 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - travis_retry composer global require "phpunit/phpunit=5.5.*"
  - travis_retry composer global require "squizlabs/php_codesniffer=*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry mysql -u root -e 'CREATE DATABASE IF NOT EXISTS ownpass;'
  - cp config/autoload/apigility.local.php.dist config/autoload/apigility.local.php
  - cp config/autoload/doctrine.local.php.dist config/autoload/doctrine.local.php
  - cp config/autoload/ownpass.local.php.dist config/autoload/ownpass.local.php
  - sed -i "s|'username' => ''|'username' => 'root'|" config/autoload/apigility.local.php
  - sed -i "s|'user' => ''|'user' => 'root'|" config/autoload/doctrine.local.php
  - sed -i "s|'password' => ''|'password' => 'ownpass'|" config/autoload/ownpass.local.php
  - php public/index.php orm:schema-tool:drop --force
  - php public/index.php orm:schema-tool:create
  - php public/index.php orm:validate-schema

script:
  - phpcs
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
  irc: "irc.freenode.org#ownpass"
