<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('OwnPass');

        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <?= $this->content ?>

        <?= $this->inlineScript() ?>
    </body>
</html>
