<?php
/**
 * This file is part of Own Pass. (https://github.com/ownpass/)
 *
 * @link https://github.com/ownpass/ownpass for the canonical source repository
 * @copyright Copyright (c) 2016-2017 Own Pass. (https://github.com/ownpass/)
 * @license https://raw.githubusercontent.com/ownpass/ownpass/master/LICENSE MIT
 */

return [
    'Zend\\Cache',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Mvc\\I18n',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'Zend\\Cache',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Mvc\\I18n',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'DoctrineModule',
    'DoctrineORMModule',
    'ZfrCors',
    'ZF\\HttpCache',
    'Zend\\Cache',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Paginator',
    'Zend\\Serializer',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\Apigility\\Documentation',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'OwnPassApplication',
    'OwnPassCredential',
    'OwnPassOAuth',
    'OwnPassUser',
];
