<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'DoctrineModule',
    'DoctrineORMModule',
    'ZfrCors',
    'ZF\\HttpCache',
    'Zend\\Cache',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\InputFilter',
    'Zend\\I18n',
    'Zend\\Log',
    'Zend\\Paginator',
    'Zend\\Serializer',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\Apigility\\Documentation',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'OwnPassApplication',
    'OwnPassCredential',
    'OwnPassOAuth',
    'OwnPassUser',
];
